Vagrant.configure("2") do |config|
  config.vm.box = "fedora/35-cloud-base"

  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose

  # Shared folders
  config.vm.synced_folder "~/git", "/home/vagrant/git"
  config.vm.synced_folder "~/.vim", "/home/vagrant/.vim"
  
  config.vm.provision "file", source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"
  config.vm.provision "file", source: "~/.vimrc", destination: "/home/vagrant/.vimrc"
  config.vm.provision "file", source: "~/tools/podman/.bash_profile", destination: "/home/vagrant/.bash_profile"

  # SSH Key Forwarding
  config.ssh.private_key_path = "~/.ssh/id_ed25519"
  config.ssh.forward_agent = true
  
  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "16384"
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y podman git vim make

    groupadd -f -r podman

    #systemctl edit podman.socket
    mkdir -p /etc/systemd/system/podman.socket.d
    cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
    systemctl daemon-reload
    echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
    sudo systemd-tmpfiles --create

    systemctl enable podman.socket
    systemctl start podman.socket

    usermod -aG podman $SUDO_USER
  SHELL
end
